dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update conda
  - conda create -n taxbrain-dev python=$TRAVIS_PYTHON_VERSION;
  - conda init bash
  - conda activate taxbrain-dev
  - conda env update -f environment.yml
  - pip install -e .

script:
  - pytest -v