package:
  name: taxbrain
  version: 0.0.0

requirements:
  build:
    - python
    - "taxcalc>1.1.0"
    - "behresp>=0.7.0"
    - dask

  run:
    - python
    - "taxcalc>1.1.0"
    - "behresp>=0.7.0"
    - dask

about:
  home: https://github.com/PSLmodels/Tax-Brain