package:
  name: taxbrain
  version: 0.0.0

requirements:
  build:
    - python
    - "taxcalc>=3.0.0"
    - "behresp>=0.11.0"
    - dask
    - bokeh
    - markdown
    - tabulate
    - pypandoc
    - matplotlib
    - "numpy>=1.14"

  run:
    - python
    - "taxcalc>=3.0.0"
    - "behresp>=0.11.0"
    - dask
    - bokeh
    - markdown
    - tabulate
    - pypandoc
    - matplotlib
    - "numpy>=1.14"

about:
  home: https://github.com/PSLmodels/Tax-Brain
