package:
  name: taxbrain
  version: 0.0.0

requirements:
  build:
    - python
    - "taxcalc>=2.2.0"
    - "behresp>=0.8.0"
    - dask

  run:
    - python
    - "taxcalc>=2.2.0"
    - "behresp>=0.8.0"
    - dask
    - bokeh

about:
  home: https://github.com/PSLmodels/Tax-Brain